### ISSUE TITLE
Assignment B1 Feedback

### ISSUE THREAD

**Issue by iciarfernandez** [stat545ubc-2021/functions-Yixuan-L#1]
Hey Yixuan,

Awesome work for Assignment B-1! 🎉  A few comments below, please let me know if you have any questions:

### Tidy Submission

- No information on how to run the contents of the repo in the README (from instructions: ""some key things they should know about how to use the files in the repository."")

### Exercise 1

- Consider modifying the function to give users the option to deal with NAs as they prefer!

- Your first error message indicates to the user what the class of their argument is, but the second error message doesn't (instead just says ""please input again""), I would keep them consistent and have both return the class of the argument since it's then easier for the user of the function to pick up what's wrong and fix it. 

### Exercise 2

- Use @param instead of @params in the documentation (small error but would give you trouble when creating the package for B-2!). 

- If you decide to keep na.rm = TRUE without user options, I would explicitly explain that function behaviour in your documentation, maybe using the @detail tag.

- @title is not a roxygen2 tag to my knowledge, the title and description are usually just written like this:

```
`#' This is the title.
#'
#' This is the description. (or you can use the @description tag)
#'
#' These are further details. (you can use @details tag)
#'
#' @param x description here`
```

### Exercise 4

- Your first and second `expect_()` tests are somewhat redundant with each other since you're essentially checking for the same thing with two different arguments, you could've tried doing an `expect_identical()` instead using for example the reference dataframe (`storeys_stat`) that you used in your examples (no points deducted, but just a suggestion to keep your tests varied)

Everything else is perfect!

Thanks,
Icíar

**Comment by Yixuan-L** [comment]
Oh I see. Thanks, Icíar~
